version: '3.2'
services:
    coog:
        image: coopengohub/coog:${COOG_VERSION}
        build:
            context: .
            args:
                - ep=$ep
            dockerfile: docker/coog/Dockerfile
    coog-static:
        image: coopengohub/static:${COOG_STATIC_VERSION}
        build:
            context: .
            dockerfile: docker/static/Dockerfile
