version: '3.2'
services:
    coog:
        image: coopengohub/coog${CUSTOMER}:${COOG_VERSION}
        build:
            context: .
            dockerfile: docker/coog/DockerfileCustomer
            args:
                IMAGE: coopengohub/coog:${COOG_VERSION}
